query {
    viewer {
        name
        repositories(last: 30) {
            nodes {
                name
                createdAt
                updatedAt
                pushedAt
                description
                id
                url
                readme: object(expression: "master:README.md") {
                    ... on Blob {
                        text
                    }
                }
            }
        }
    }
}
